### ISSUE TITLE
Redis Sorted Set 기능을 이용한 대기열 API 개발

### ISSUE THREAD

**Issue by junha-ahn** [f-lab-clone/queuing-system#1]
# Description

Redis SortSet 기능을 이용한 대기열 API 개발

![image](https://github.com/f-lab-clone/queuing-system/assets/41976906/a40cead4-a8fc-4341-87d5-5bb64f9221a3)

> https://github.com/f-lab-clone/ticketing-backend/issues/72#issuecomment-1763307025

# To do
- [x] 발행 API
- [x] 확인 API

# Test Checklist

**Comment by ParkJeongseop** [comment]
한번 사용한 티켓은 재사용불가한가요?

**Comment by junha-ahn** [comment]
오 좋은 지적이네요. 예약 서버에서 요청시 삭제하도록 로직변경하겠습니다
